scripts: [
    '/home/mitmproxy/addons/block-telegram.py',
    '/home/mitmproxy/addons/mail-intercept.py',
    '/home/mitmproxy/addons/ipinfo.py',
    '/home/mitmproxy/addons/bininfo.py'
]
ssl_insecure: true
