services:
  webserver:
    build:
      context: ./docker/web
    depends_on:
      - mitmproxy
    container_name: 'webserver'
    hostname: 'phishlake.local'
    restart: 'always'
    environment:
      - http_proxy=http://mitmproxy:8080
      - HTTPS_PROXY=http://mitmproxy:8080
      - XDEBUG_CONFIG="remote_host=localhost remote_port=9000 remote_enable=1"
    links:
      - mitmproxy
      - db
    volumes:
      - ./www:/var/www/html
      - ./configs/web/vhosts:/etc/apache2/sites-enabled/
      - ./configs/php/php.ini:/usr/local/etc/php/php.ini
      - ./configs/php/patch.php:/usr/local/bin/patch.php
      - ./configs/php/unpatch.php:/usr/local/bin/unpatch.php
      - ./logs:/var/log/phishlake/
      - mitm-volume:/usr/local/share/ca-certificates/extra/
    command: >
      bash -c "cp /usr/local/share/ca-certificates/extra/mitmproxy-ca-cert.{pem,crt} &&
      update-ca-certificates --verbose &&
      chmod -R 777 /var/log/phishlake &&
      apache2-foreground"
    networks:
      phishlake_network:
        aliases:
          - phishlake.local

  mitmproxy:
    build:
      context: ./docker/mitmproxy
    container_name: 'mitmproxy'
    restart: 'always'
    command: > 
      bash -c "mitmweb --web-host 0.0.0.0 --set confdir=/home/mitmproxy/.mitmproxy --set web_password=mitmweb --ignore-hosts='(google\.com|googleapis\.com|me\.gvt1\.com|gstatic\.com)' &&
      chmod -R 777 /home/mitmproxy/logs/"
    ports:
      - "8080:8081"
    tty: true
    volumes:
      - mitm-volume:/home/mitmproxy/.mitmproxy/
      - ./configs/mitmproxy/config.yaml:/home/mitmproxy/.mitmproxy/config.yaml
      - ./logs:/home/mitmproxy/logs
    networks:
      - phishlake_network

  browser:
    build:
      context: ./docker/docker-chromium
      shm_size: '2gb'
    ports:
      - "3000:3000"
    container_name: 'chromium'
    volumes:
      - browser-volume:/config:rw
      - mitm-volume:/config/certs/
    depends_on:
      - mitmproxy
    links:
      - mitmproxy
      - webserver
    networks:
      - phishlake_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - http_proxy=http://mitmproxy:8080
      - https_proxy=http://mitmproxy:8080
      - CHROME_OPTS=--proxy-server="http=mitmproxy:8080;https=mitmproxy:8080" --disable-features=CaptivePortalDetection
    restart: unless-stopped

  db:
    image: mysql:8.4.5
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    container_name: 'db'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: phishlake_db
      MYSQL_USER: phishlake
      MYSQL_PASSWORD: password

volumes:
  mitm-volume:
  browser-volume:
  db_data:

networks:
  phishlake_network:
